name: grove_rewards
description: "\"Tap&Collect offers a seamless, eco-friendly loyalty experience for small businesses, blending the warmth of a local cafe with modern NFC technology to track points and redeem rewards effortlessly.\""
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  nfc_manager: ^4.0.0
  shared_preferences: ^2.2.2
  go_router: ^17.0.0
  uuid: ^4.0.0
  sqflite: ^2.2.8
  path_provider: ^2.0.0
  path: ^1.9.0
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.0.0
  logger: ^2.0.0
  mongo_dart: ^0.10.5
  flutter_dotenv: ^5.1.0
  http: ^1.6.0
  image_picker: ^0.8.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true

dependency_overrides:
  sqflite_android: 2.4.1