name: backend_my_api
description: A server for Grove Rewards.
vversion: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  # make sure this is just 'dotenv', NOT 'flutter_dotenv'
  dotenv: ^4.2.0
  mongo_dart: ^0.10.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^2.0.0

executables:
  server: bin/server.dart
